import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {bold} from "next/dist/lib/picocolors";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
        <Head>
            <title>Beatriz Bizatto</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
            <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'/>
        </Head>
        <main className={styles.main}>
            <div className={styles.header}>
              <span><b>Sobre Mim</b></span>
              <span><b>Skills</b></span>
              <span><b>Experiência</b></span>
              <span><b>Projetos</b></span>
              <span><b>Contato</b></span>
              <button><b>Currículo</b></button>
          </div>
            <div className={styles.card}>
                Hello There

            </div>
      </main>
    </>
  )
}
